name: CI

on:
  pull_request:
  push:
    branches:
      - master

jobs:
  mix_test:
    name: mix test (Elixir ${{matrix.elixir}} | Erlang/OTP ${{matrix.otp}})
    runs-on: ubuntu-latest
    continue-on-error: ${{ matrix.unsupported }}
    strategy:
      fail-fast: false
      matrix:
        include:
          - elixir: 1.7.4
            otp: 19.3.6.13
            unsupported: true
          - elixir: 1.8.2
            otp: 20.3.8.26
            unsupported: true
          - elixir: 1.9.4
            otp: 20.3.8.26
            unsupported: true
            warnings_as_errors: true # not 1.10 as its --warnigs-as-errors has bugs https://github.com/elixir-lang/elixir/issues/10073
          - elixir: 1.10.4
            otp: 21.3.8.16
            unsupported: false
          - elixir: 1.10.4
            otp: 23.0.3
            unsupported: false
            static_analysis: true
    env:
      MIX_ENV: test
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-elixir@v1
        with:
          otp-version: ${{matrix.otp}}
          elixir-version: ${{matrix.elixir}}
      - name: Install Dependencies
        run: |
          mix local.hex --force
          mix local.rebar --force
          mix deps.get --only test
      - run: mix format --check-formatted
        if: matrix.static_analysis
      - run: mix compile --warnings-as-errors
        if: matrix.warnings_as_errors
      - run: mix test
      - run: mix credo --all --strict
        if: matrix.static_analysis
      - run: mix dialyzer
        if: matrix.static_analysis
